### ISSUE TITLE
hostname and addresses are always emtpy

### ISSUE THREAD

**Issue by Melf11** [ecnepsnai/BonjourSwift#2]
hi, i want to scan my bonjour services and than connect via the hostname to the socket. so far it works if the service.name is exactly the hostname. trying to get service.hostname or the service.addresses returns me always a nil for the hostname or an empty addresses array.

i put the services into a local "var bonjourServices = [NetService]()" and than call the hostnames later from the local one:
```
// scanning for services, delete old bonjourServices Array and fill it with new discovered services
    func putServicesToArray(){
        let browser: Bonjour = Bonjour()
        
        _ = browser.findService(Bonjour.Services.Remote_Audio_Output, domain: Bonjour.LocalDomain) { (services) in
            
            self.bonjourServices.removeAll()
            
            for service in browser.services {
                
                if !(self.bonjourServices.contains(service)) {
                    
                    self.bonjourServices.append(service)
                    
                }
            }
        }
    }
```
it would be very nice, if you can give me a hint

**Comment by bannn-1018** [comment]
I have the same problem too.

**Comment by ecnepsnai** [comment]
According to the Apple documentation for (NS)NetService, hostname and addresses will be nil until you've resolved the service. https://developer.apple.com/documentation/foundation/netservice/1413300-hostname

At the moment, BonjourSwift does not resolve the services for you. You must resolve each service yourself using `resolve(withTimeout:)` as described here: https://developer.apple.com/documentation/foundation/netservice/1416564-resolve

I will investigate how to resolve the services for you within the module.
